#include "saveGraphTest.h"
#include <cstdlib>
#include <ctime>

#include <tulip/Graph.h>

#include <QtScript/QScriptEngine>
#include <QTextStream>
#include <QFile>

CPPUNIT_TEST_SUITE_REGISTRATION(saveGraphTest);

void saveGraphTest::setUp()
{
	_engine = new QScriptEngine();
	_graph = tlp::newGraph();

	_savedFile = "(tlp \"2.0\" \
		(date \"12-10-2008\") \
		(comments \"This file was generated by Tulip.\") \
		;(nodes <node_id> <node_id> ...) \
		(nodes ) \
		;(edge <edge_id> <source_id> <target_id>) \
		 \
		 \
		(property  0 color \"viewBorderColor\" \
		(default \"(0,0,0,255)\" \"(0,0,0,255)\") \
		) \
		(property  0 double \"viewBorderWidth\" \
		(default \"0\" \"0\") \
		) \
		(property  0 color \"viewColor\" \
		(default \"(255,0,0,255)\" \"(0,0,0,255)\") \
		) \
		(property  0 string \"viewLabel\" \
		(default \"\" \"\") \
		) \
		(property  0 color \"viewLabelColor\" \
		(default \"(0,0,0,255)\" \"(0,0,0,255)\") \
		) \
		(property  0 int \"viewLabelPosition\" \
		(default \"0\" \"0\") \
		) \
		(property  0 layout \"viewLayout\" \
		(default \"(291,543,701)\" \"()\") \
		) \
		(property  0 graph \"viewMetaGraph\" \
		(default \"\" \"\") \
		) \
		(property  0 double \"viewRotation\" \
		(default \"0\" \"0\") \
		) \
		(property  0 bool \"viewSelection\" \
		(default \"false\" \"false\") \
		) \
		(property  0 int \"viewShape\" \
		(default \"1\" \"0\") \
		) \
		(property  0 size \"viewSize\" \
		(default \"(1,1,1)\" \"(0.125,0.125,0.5)\") \
		) \
		(property  0 string \"viewTexture\" \
		(default \"\" \"\") \
		) \
		(attributes \
		(string \"name\" \"graphe de test sauvegarde\") \
		) \
		)";

}

void saveGraphTest::tearDown()
{
	delete _graph;
	delete _engine;
}

void saveGraphTest::saveTest()
{
	const std::string filename = "grapheGenial.tlp";

	_engine->evaluate(QString::fromStdString("var g = newGraph(); saveGraph(\""+filename+"\");"));

	QFile file(QString::fromStdString(filename));
	file.open(QFile::ReadOnly);
	QTextStream data(&file);

	CPPUNIT_ASSERT_EQUAL(_savedFile , data.readAll().toStdString());
}
